name: Build Electron App

on:
  push:
    branches:
      - main

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Build app
        run: npm run make

      - name: Upload artefatos
        uses: actions/upload-artifact@v4
        with:
          name: electron-build-${{ matrix.os }}
          path: out/make/**